import Head from "next/head";

import { DemoComponent } from "@/components/molecules/DemoComponent/DemoComponent";

export default function Demo() {
  return (
    <>
      <Head>
        <title>CW React Date Picker - Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <article className="w-full pt-20 !font-poppins">
      <DemoComponent />
    </article>
      </main>
    </>
  );
}
