import Head from "next/head";
import Link from "next/link";
import { Layout } from "@/components/layout";
import { CustomDatePicker } from "@/components/atoms/DatePicker/DatePicker";

export default function Home() {
  const endDateLimit = new Date();
  endDateLimit.setDate(endDateLimit.getDate() + 30);
  return (
    <>
      <Head>
        <title>CW React Date Picker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <CustomDatePicker 
          isEndDate 
          startDatePlaceHolder="Start Date"
          endDatePlaceHolder="End Date"
          calendarStartFromMondayDay
          endDateLimit={endDateLimit}
          markSundayAsRed
        />
        <Link href="/demo">
          <p className="mt-4 text-center text-xs px-2 py-2">Would you like to check on Demo? <span className="text-blue-500 font-semibold hover:underline">Click here for Demo</span></p>
        </Link>
      </Layout>
    </>
  );
}
